// Comprehensive list of countries with ISO 3166-1 alpha-2 codes
// Flag images are sourced dynamically via https://flagcdn.com/
const COUNTRIES_DATA = [
  // Europe
  { code: "al", name: "Albania", capital: "Tirana", continent: "Europe", difficulty: "medium" },
  { code: "ad", name: "Andorra", capital: "Andorra la Vella", continent: "Europe", difficulty: "hard" },
  { code: "at", name: "Austria", capital: "Vienna", continent: "Europe", difficulty: "easy" },
  { code: "by", name: "Belarus", capital: "Minsk", continent: "Europe", difficulty: "medium" },
  { code: "be", name: "Belgium", capital: "Brussels", continent: "Europe", difficulty: "easy" },
  { code: "ba", name: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe", difficulty: "medium", aliases: ["Bosnia"] },
  { code: "bg", name: "Bulgaria", capital: "Sofia", continent: "Europe", difficulty: "medium" },
  { code: "hr", name: "Croatia", capital: "Zagreb", continent: "Europe", difficulty: "easy" },
  { code: "cy", name: "Cyprus", capital: "Nicosia", continent: "Europe", difficulty: "medium" },
  { code: "cz", name: "Czech Republic", capital: "Prague", continent: "Europe", difficulty: "easy", aliases: ["Czechia"] },
  { code: "dk", name: "Denmark", capital: "Copenhagen", continent: "Europe", difficulty: "easy" },
  { code: "ee", name: "Estonia", capital: "Tallinn", continent: "Europe", difficulty: "medium" },
  { code: "fi", name: "Finland", capital: "Helsinki", continent: "Europe", difficulty: "easy" },
  { code: "fr", name: "France", capital: "Paris", continent: "Europe", difficulty: "easy" },
  { code: "de", name: "Germany", capital: "Berlin", continent: "Europe", difficulty: "easy" },
  { code: "gr", name: "Greece", capital: "Athens", continent: "Europe", difficulty: "easy" },
  { code: "hu", name: "Hungary", capital: "Budapest", continent: "Europe", difficulty: "medium" },
  { code: "is", name: "Iceland", capital: "Reykjavik", continent: "Europe", difficulty: "easy" },
  { code: "ie", name: "Ireland", capital: "Dublin", continent: "Europe", difficulty: "easy" },
  { code: "it", name: "Italy", capital: "Rome", continent: "Europe", difficulty: "easy" },
  { code: "xk", name: "Kosovo", capital: "Pristina", continent: "Europe", difficulty: "medium" },
  { code: "lv", name: "Latvia", capital: "Riga", continent: "Europe", difficulty: "medium" },
  { code: "li", name: "Liechtenstein", capital: "Vaduz", continent: "Europe", difficulty: "hard" },
  { code: "lt", name: "Lithuania", capital: "Vilnius", continent: "Europe", difficulty: "medium" },
  { code: "lu", name: "Luxembourg", capital: "Luxembourg", continent: "Europe", difficulty: "medium" },
  { code: "mt", name: "Malta", capital: "Valletta", continent: "Europe", difficulty: "medium" },
  { code: "md", name: "Moldova", capital: "Chisinau", continent: "Europe", difficulty: "hard" },
  { code: "mc", name: "Monaco", capital: "Monaco", continent: "Europe", difficulty: "medium" },
  { code: "me", name: "Montenegro", capital: "Podgorica", continent: "Europe", difficulty: "medium" },
  { code: "nl", name: "Netherlands", capital: "Amsterdam", continent: "Europe", difficulty: "easy", aliases: ["Holland"] },
  { code: "mk", name: "North Macedonia", capital: "Skopje", continent: "Europe", difficulty: "medium", aliases: ["Macedonia"] },
  { code: "no", name: "Norway", capital: "Oslo", continent: "Europe", difficulty: "easy" },
  { code: "pl", name: "Poland", capital: "Warsaw", continent: "Europe", difficulty: "easy" },
  { code: "pt", name: "Portugal", capital: "Lisbon", continent: "Europe", difficulty: "easy" },
  { code: "ro", name: "Romania", capital: "Bucharest", continent: "Europe", difficulty: "medium" },
  { code: "ru", name: "Russia", capital: "Moscow", continent: "Europe", difficulty: "easy" },
  { code: "sm", name: "San Marino", capital: "San Marino", continent: "Europe", difficulty: "hard" },
  { code: "rs", name: "Serbia", capital: "Belgrade", continent: "Europe", difficulty: "medium" },
  { code: "sk", name: "Slovakia", capital: "Bratislava", continent: "Europe", difficulty: "medium" },
  { code: "si", name: "Slovenia", capital: "Ljubljana", continent: "Europe", difficulty: "medium" },
  { code: "es", name: "Spain", capital: "Madrid", continent: "Europe", difficulty: "easy" },
  { code: "se", name: "Sweden", capital: "Stockholm", continent: "Europe", difficulty: "easy" },
  { code: "ch", name: "Switzerland", capital: "Bern", continent: "Europe", difficulty: "easy" },
  { code: "ua", name: "Ukraine", capital: "Kyiv", continent: "Europe", difficulty: "easy" },
  { code: "gb", name: "United Kingdom", capital: "London", continent: "Europe", difficulty: "easy", aliases: ["UK", "Great Britain", "Britain"] },
  { code: "va", name: "Vatican City", capital: "Vatican City", continent: "Europe", difficulty: "hard", aliases: ["Holy See"] },

  // Asia
  { code: "af", name: "Afghanistan", capital: "Kabul", continent: "Asia", difficulty: "medium" },
  { code: "am", name: "Armenia", capital: "Yerevan", continent: "Asia", difficulty: "medium" },
  { code: "az", name: "Azerbaijan", capital: "Baku", continent: "Asia", difficulty: "medium" },
  { code: "bh", name: "Bahrain", capital: "Manama", continent: "Asia", difficulty: "medium" },
  { code: "bd", name: "Bangladesh", capital: "Dhaka", continent: "Asia", difficulty: "medium" },
  { code: "bt", name: "Bhutan", capital: "Thimphu", continent: "Asia", difficulty: "medium" },
  { code: "bn", name: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia", difficulty: "hard" },
  { code: "kh", name: "Cambodia", capital: "Phnom Penh", continent: "Asia", difficulty: "medium" },
  { code: "cn", name: "China", capital: "Beijing", continent: "Asia", difficulty: "easy" },
  { code: "ge", name: "Georgia", capital: "Tbilisi", continent: "Asia", difficulty: "medium" },
  { code: "in", name: "India", capital: "New Delhi", continent: "Asia", difficulty: "easy" },
  { code: "id", name: "Indonesia", capital: "Jakarta", continent: "Asia", difficulty: "medium" },
  { code: "ir", name: "Iran", capital: "Tehran", continent: "Asia", difficulty: "medium" },
  { code: "iq", name: "Iraq", capital: "Baghdad", continent: "Asia", difficulty: "medium" },
  { code: "il", name: "Israel", capital: "Jerusalem", continent: "Asia", difficulty: "easy" },
  { code: "jp", name: "Japan", capital: "Tokyo", continent: "Asia", difficulty: "easy" },
  { code: "jo", name: "Jordan", capital: "Amman", continent: "Asia", difficulty: "medium" },
  { code: "kz", name: "Kazakhstan", capital: "Astana", continent: "Asia", difficulty: "medium" },
  { code: "kw", name: "Kuwait", capital: "Kuwait City", continent: "Asia", difficulty: "medium" },
  { code: "kg", name: "Kyrgyzstan", capital: "Bishkek", continent: "Asia", difficulty: "hard" },
  { code: "la", name: "Laos", capital: "Vientiane", continent: "Asia", difficulty: "medium" },
  { code: "lb", name: "Lebanon", capital: "Beirut", continent: "Asia", difficulty: "medium" },
  { code: "my", name: "Malaysia", capital: "Kuala Lumpur", continent: "Asia", difficulty: "medium" },
  { code: "mv", name: "Maldives", capital: "Male", continent: "Asia", difficulty: "medium" },
  { code: "mn", name: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", difficulty: "medium" },
  { code: "mm", name: "Myanmar", capital: "Naypyidaw", continent: "Asia", difficulty: "medium", aliases: ["Burma"] },
  { code: "np", name: "Nepal", capital: "Kathmandu", continent: "Asia", difficulty: "easy" },
  { code: "kp", name: "North Korea", capital: "Pyongyang", continent: "Asia", difficulty: "easy" },
  { code: "om", name: "Oman", capital: "Muscat", continent: "Asia", difficulty: "medium" },
  { code: "pk", name: "Pakistan", capital: "Islamabad", continent: "Asia", difficulty: "medium" },
  { code: "ps", name: "Palestine", capital: "Ramallah", continent: "Asia", difficulty: "medium" },
  { code: "ph", name: "Philippines", capital: "Manila", continent: "Asia", difficulty: "medium" },
  { code: "qa", name: "Qatar", capital: "Doha", continent: "Asia", difficulty: "medium" },
  { code: "sa", name: "Saudi Arabia", capital: "Riyadh", continent: "Asia", difficulty: "easy" },
  { code: "sg", name: "Singapore", capital: "Singapore", continent: "Asia", difficulty: "easy" },
  { code: "kr", name: "South Korea", capital: "Seoul", continent: "Asia", difficulty: "easy", aliases: ["Korea"] },
  { code: "lk", name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia", difficulty: "medium" },
  { code: "sy", name: "Syria", capital: "Damascus", continent: "Asia", difficulty: "medium" },
  { code: "tw", name: "Taiwan", capital: "Taipei", continent: "Asia", difficulty: "easy" },
  { code: "tj", name: "Tajikistan", capital: "Dushanbe", continent: "Asia", difficulty: "hard" },
  { code: "th", name: "Thailand", capital: "Bangkok", continent: "Asia", difficulty: "medium" },
  { code: "tl", name: "Timor-Leste", capital: "Dili", continent: "Asia", difficulty: "hard", aliases: ["East Timor"] },
  { code: "tr", name: "Turkey", capital: "Ankara", continent: "Asia", difficulty: "easy", aliases: ["Turkiye"] },
  { code: "tm", name: "Turkmenistan", capital: "Ashgabat", continent: "Asia", difficulty: "hard" },
  { code: "ae", name: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia", difficulty: "medium", aliases: ["UAE"] },
  { code: "uz", name: "Uzbekistan", capital: "Tashkent", continent: "Asia", difficulty: "hard" },
  { code: "vn", name: "Vietnam", capital: "Hanoi", continent: "Asia", difficulty: "easy" },
  { code: "ye", name: "Yemen", capital: "Sana'a", continent: "Asia", difficulty: "medium" },

  // Americas
  { code: "ag", name: "Antigua and Barbuda", capital: "St. John's", continent: "Americas", difficulty: "hard" },
  { code: "ar", name: "Argentina", capital: "Buenos Aires", continent: "Americas", difficulty: "easy" },
  { code: "bs", name: "Bahamas", capital: "Nassau", continent: "Americas", difficulty: "medium" },
  { code: "bb", name: "Barbados", capital: "Bridgetown", continent: "Americas", difficulty: "medium" },
  { code: "bz", name: "Belize", capital: "Belmopan", continent: "Americas", difficulty: "hard" },
  { code: "bo", name: "Bolivia", capital: "Sucre", continent: "Americas", difficulty: "medium" },
  { code: "br", name: "Brazil", capital: "Brasilia", continent: "Americas", difficulty: "easy" },
  { code: "ca", name: "Canada", capital: "Ottawa", continent: "Americas", difficulty: "easy" },
  { code: "cl", name: "Chile", capital: "Santiago", continent: "Americas", difficulty: "medium" },
  { code: "co", name: "Colombia", capital: "Bogota", continent: "Americas", difficulty: "medium" },
  { code: "cr", name: "Costa Rica", capital: "San Jose", continent: "Americas", difficulty: "medium" },
  { code: "cu", name: "Cuba", capital: "Havana", continent: "Americas", difficulty: "medium" },
  { code: "dm", name: "Dominica", capital: "Roseau", continent: "Americas", difficulty: "hard" },
  { code: "do", name: "Dominican Republic", capital: "Santo Domingo", continent: "Americas", difficulty: "medium" },
  { code: "ec", name: "Ecuador", capital: "Quito", continent: "Americas", difficulty: "medium" },
  { code: "sv", name: "El Salvador", capital: "San Salvador", continent: "Americas", difficulty: "medium" },
  { code: "gd", name: "Grenada", capital: "St. George's", continent: "Americas", difficulty: "hard" },
  { code: "gt", name: "Guatemala", capital: "Guatemala City", continent: "Americas", difficulty: "medium" },
  { code: "gy", name: "Guyana", capital: "Georgetown", continent: "Americas", difficulty: "hard" },
  { code: "ht", name: "Haiti", capital: "Port-au-Prince", continent: "Americas", difficulty: "medium" },
  { code: "hn", name: "Honduras", capital: "Tegucigalpa", continent: "Americas", difficulty: "medium" },
  { code: "jm", name: "Jamaica", capital: "Kingston", continent: "Americas", difficulty: "easy" },
  { code: "mx", name: "Mexico", capital: "Mexico City", continent: "Americas", difficulty: "easy" },
  { code: "ni", name: "Nicaragua", capital: "Managua", continent: "Americas", difficulty: "medium" },
  { code: "pa", name: "Panama", capital: "Panama City", continent: "Americas", difficulty: "medium" },
  { code: "py", name: "Paraguay", capital: "Asuncion", continent: "Americas", difficulty: "medium" },
  { code: "pe", name: "Peru", capital: "Lima", continent: "Americas", difficulty: "medium" },
  { code: "kn", name: "Saint Kitts and Nevis", capital: "Basseterre", continent: "Americas", difficulty: "hard" },
  { code: "lc", name: "Saint Lucia", capital: "Castries", continent: "Americas", difficulty: "hard" },
  { code: "vc", name: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "Americas", difficulty: "hard" },
  { code: "sr", name: "Suriname", capital: "Paramaribo", continent: "Americas", difficulty: "hard" },
  { code: "tt", name: "Trinidad and Tobago", capital: "Port of Spain", continent: "Americas", difficulty: "medium" },
  { code: "us", name: "United States", capital: "Washington, D.C.", continent: "Americas", difficulty: "easy", aliases: ["USA", "America"] },
  { code: "uy", name: "Uruguay", capital: "Montevideo", continent: "Americas", difficulty: "medium" },
  { code: "ve", name: "Venezuela", capital: "Caracas", continent: "Americas", difficulty: "medium" },

  // Africa
  { code: "dz", name: "Algeria", capital: "Algiers", continent: "Africa", difficulty: "medium" },
  { code: "ao", name: "Angola", capital: "Luanda", continent: "Africa", difficulty: "medium" },
  { code: "bj", name: "Benin", capital: "Porto-Novo", continent: "Africa", difficulty: "hard" },
  { code: "bw", name: "Botswana", capital: "Gaborone", continent: "Africa", difficulty: "medium" },
  { code: "bf", name: "Burkina Faso", capital: "Ouagadougou", continent: "Africa", difficulty: "hard" },
  { code: "bi", name: "Burundi", capital: "Gitega", continent: "Africa", difficulty: "hard" },
  { code: "cv", name: "Cabo Verde", capital: "Praia", continent: "Africa", difficulty: "hard", aliases: ["Cape Verde"] },
  { code: "cm", name: "Cameroon", capital: "Yaounde", continent: "Africa", difficulty: "medium" },
  { code: "cf", name: "Central African Republic", capital: "Bangui", continent: "Africa", difficulty: "hard" },
  { code: "td", name: "Chad", capital: "N'Djamena", continent: "Africa", difficulty: "hard" },
  { code: "km", name: "Comoros", capital: "Moroni", continent: "Africa", difficulty: "hard" },
  { code: "cg", name: "Congo", capital: "Brazzaville", continent: "Africa", difficulty: "hard", aliases: ["Republic of the Congo"] },
  { code: "cd", name: "DR Congo", capital: "Kinshasa", continent: "Africa", difficulty: "medium", aliases: ["Democratic Republic of the Congo", "DRC"] },
  { code: "ci", name: "Ivory Coast", capital: "Yamoussoukro", continent: "Africa", difficulty: "medium", aliases: ["Cote d'Ivoire"] },
  { code: "dj", name: "Djibouti", capital: "Djibouti", continent: "Africa", difficulty: "hard" },
  { code: "eg", name: "Egypt", capital: "Cairo", continent: "Africa", difficulty: "easy" },
  { code: "gq", name: "Equatorial Guinea", capital: "Malabo", continent: "Africa", difficulty: "hard" },
  { code: "er", name: "Eritrea", capital: "Asmara", continent: "Africa", difficulty: "hard" },
  { code: "sz", name: "Eswatini", capital: "Mbabane", continent: "Africa", difficulty: "hard", aliases: ["Swaziland"] },
  { code: "et", name: "Ethiopia", capital: "Addis Ababa", continent: "Africa", difficulty: "medium" },
  { code: "ga", name: "Gabon", capital: "Libreville", continent: "Africa", difficulty: "hard" },
  { code: "gm", name: "Gambia", capital: "Banjul", continent: "Africa", difficulty: "hard" },
  { code: "gh", name: "Ghana", capital: "Accra", continent: "Africa", difficulty: "medium" },
  { code: "gn", name: "Guinea", capital: "Conakry", continent: "Africa", difficulty: "hard" },
  { code: "gw", name: "Guinea-Bissau", capital: "Bissau", continent: "Africa", difficulty: "hard" },
  { code: "ke", name: "Kenya", capital: "Nairobi", continent: "Africa", difficulty: "medium" },
  { code: "ls", name: "Lesotho", capital: "Maseru", continent: "Africa", difficulty: "hard" },
  { code: "lr", name: "Liberia", capital: "Monrovia", continent: "Africa", difficulty: "hard" },
  { code: "ly", name: "Libya", capital: "Tripoli", continent: "Africa", difficulty: "medium" },
  { code: "mg", name: "Madagascar", capital: "Antananarivo", continent: "Africa", difficulty: "medium" },
  { code: "mw", name: "Malawi", capital: "Lilongwe", continent: "Africa", difficulty: "hard" },
  { code: "ml", name: "Mali", capital: "Bamako", continent: "Africa", difficulty: "hard" },
  { code: "mr", name: "Mauritania", capital: "Nouakchott", continent: "Africa", difficulty: "hard" },
  { code: "mu", name: "Mauritius", capital: "Port Louis", continent: "Africa", difficulty: "medium" },
  { code: "ma", name: "Morocco", capital: "Rabat", continent: "Africa", difficulty: "easy" },
  { code: "mz", name: "Mozambique", capital: "Maputo", continent: "Africa", difficulty: "medium" },
  { code: "na", name: "Namibia", capital: "Windhoek", continent: "Africa", difficulty: "medium" },
  { code: "ne", name: "Niger", capital: "Niamey", continent: "Africa", difficulty: "hard" },
  { code: "ng", name: "Nigeria", capital: "Abuja", continent: "Africa", difficulty: "medium" },
  { code: "rw", name: "Rwanda", capital: "Kigali", continent: "Africa", difficulty: "medium" },
  { code: "st", name: "Sao Tome and Principe", capital: "Sao Tome", continent: "Africa", difficulty: "hard" },
  { code: "sn", name: "Senegal", capital: "Dakar", continent: "Africa", difficulty: "medium" },
  { code: "sc", name: "Seychelles", capital: "Victoria", continent: "Africa", difficulty: "medium" },
  { code: "sl", name: "Sierra Leone", capital: "Freetown", continent: "Africa", difficulty: "hard" },
  { code: "so", name: "Somalia", capital: "Mogadishu", continent: "Africa", difficulty: "medium" },
  { code: "za", name: "South Africa", capital: "Pretoria", continent: "Africa", difficulty: "easy" },
  { code: "ss", name: "South Sudan", capital: "Juba", continent: "Africa", difficulty: "hard" },
  { code: "sd", name: "Sudan", capital: "Khartoum", continent: "Africa", difficulty: "hard" },
  { code: "tz", name: "Tanzania", capital: "Dodoma", continent: "Africa", difficulty: "medium" },
  { code: "tg", name: "Togo", capital: "Lome", continent: "Africa", difficulty: "hard" },
  { code: "tn", name: "Tunisia", capital: "Tunis", continent: "Africa", difficulty: "medium" },
  { code: "ug", name: "Uganda", capital: "Kampala", continent: "Africa", difficulty: "medium" },
  { code: "zm", name: "Zambia", capital: "Lusaka", continent: "Africa", difficulty: "medium" },
  { code: "zw", name: "Zimbabwe", capital: "Harare", continent: "Africa", difficulty: "medium" },

  // Oceania
  { code: "au", name: "Australia", capital: "Canberra", continent: "Oceania", difficulty: "easy" },
  { code: "fj", name: "Fiji", capital: "Suva", continent: "Oceania", difficulty: "medium" },
  { code: "ki", name: "Kiribati", capital: "South Tarawa", continent: "Oceania", difficulty: "hard" },
  { code: "mh", name: "Marshall Islands", capital: "Majuro", continent: "Oceania", difficulty: "hard" },
  { code: "fm", name: "Micronesia", capital: "Palikir", continent: "Oceania", difficulty: "hard" },
  { code: "nr", name: "Nauru", capital: "Yaren", continent: "Oceania", difficulty: "hard" },
  { code: "nz", name: "New Zealand", capital: "Wellington", continent: "Oceania", difficulty: "easy" },
  { code: "pw", name: "Palau", capital: "Ngerulmud", continent: "Oceania", difficulty: "hard" },
  { code: "pg", name: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania", difficulty: "medium" },
  { code: "ws", name: "Samoa", capital: "Apia", continent: "Oceania", difficulty: "medium" },
  { code: "sb", name: "Solomon Islands", capital: "Honiara", continent: "Oceania", difficulty: "hard" },
  { code: "to", name: "Tonga", capital: "Nuku'alofa", continent: "Oceania", difficulty: "hard" },
  { code: "tv", name: "Tuvalu", capital: "Funafuti", continent: "Oceania", difficulty: "hard" },
  { code: "vu", name: "Vanuatu", capital: "Port Vila", continent: "Oceania", difficulty: "hard" }
];

function getFlagUrl(code, width = 320) {
  return `https://flagcdn.com/w${width}/${code.toLowerCase()}.png`;
}

function getFlagSvgUrl(code) {
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { COUNTRIES_DATA, getFlagUrl, getFlagSvgUrl };
}
